# Generated by Django 4.2 on 2023-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['number'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='module',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Порядковый номер'),
        ),
    ]
